use sc2006;

DROP TABLE SAVED_LOCATIONS;
DROP TABLE JOINED_PARTY;
DROP TABLE PARTY_HISTORY;
DROP TABLE PARTY;
DROP TABLE USERS;

CREATE TABLE USERS (
    USER_ID int NOT NULL AUTO_INCREMENT UNIQUE,
    USERNAME varchar(255) NOT NULL,
    PASSWORD_HASH varchar(255) NOT NULL,
    EMAIL varchar(255) NOT NULL UNIQUE,
    PHONENUMBER varchar(255) NOT NULL UNIQUE,
    PRIMARY KEY (USER_ID)
);


CREATE TABLE SAVED_LOCATIONS (
    USER_ID int,
    LOCATION varchar(255) NOT NULL,
    LOCATION_COORDINATE varchar(255) NOT NULL,
    FOREIGN KEY (USER_ID)
      REFERENCES USERS(USER_ID)
);


CREATE TABLE PARTY (
    PARTY_ID int NOT NULL AUTO_INCREMENT UNIQUE,
    PARTY_LEADER int NOT NULL,
    DESTINATION varchar(255) NOT NULL,
    DESTINATION_COORDINATE varchar(255) NOT NULL,
    DESTINATION_LOCATION varchar(255) NOT NULL,
    PREFERRED_ARRIVAL_TIME datetime NOT NULL,
    STA int NOT NULL,
    FOREIGN KEY (PARTY_LEADER)
      REFERENCES USERS(USER_ID),
  PRIMARY KEY (PARTY_ID)
);

CREATE TABLE PARTY_HISTORY (
    PARTY_ID int NOT NULL,
    USER_ID int NOT NULL,
    FOREIGN KEY (PARTY_ID)
      REFERENCES PARTY(PARTY_ID),
  FOREIGN KEY (USER_ID)
      REFERENCES USERS(USER_ID)
);

CREATE TABLE JOINED_PARTY (
    PARTY_ID int NOT NULL,
    USER_ID int NOT NULL UNIQUE,
    FOREIGN KEY (PARTY_ID)
      REFERENCES PARTY(PARTY_ID),
  FOREIGN KEY (USER_ID)
      REFERENCES USERS(USER_ID)
);